In [ ]:
import numpy as np

In [ ]:
a1 = np.array( [ 80, 76, 77, 78, 79, 81, 76, 77, 79, 84, 75, 79, 76, 78 ], dtype=float )
a2 = np.array( [ 66, 69, 76, 72, 79, 77, 74, 77, 71, 79, 74, 66, 67, 78 ], dtype=float )       
a3 = np.array( [ 66, 69, 76, 72, 79, 77, 74, 77, 71, 79, 74, 66, 67, 73 ], dtype=float )   
a4 =  np.array( [ 80, 76, 77, 78, 79, 81, 76, 77, 79, 84, 75, 79, 76, 78 ], dtype=float ) 

In [ ]:
series = [a1, a2, a3, a4]
length = len(series)
for i in range(length):
  for j in range(i+1,length):
    err = np.abs(series[i] - series[j])
    log_err = np.log(err)
    output_errors = np.exp(np.median(log_err))
    print("for array", series[i]," and ", series[j])
    print(output_errors)

for array [80. 76. 77. 78. 79. 81. 76. 77. 79. 84. 75. 79. 76. 78.]  and  [66. 69. 76. 72. 79. 77. 74. 77. 71. 79. 74. 66. 67. 78.]
4.472135954999579
for array [80. 76. 77. 78. 79. 81. 76. 77. 79. 84. 75. 79. 76. 78.]  and  [66. 69. 76. 72. 79. 77. 74. 77. 71. 79. 74. 66. 67. 73.]
4.999999999999999
for array [80. 76. 77. 78. 79. 81. 76. 77. 79. 84. 75. 79. 76. 78.]  and  [80. 76. 77. 78. 79. 81. 76. 77. 79. 84. 75. 79. 76. 78.]
0.0
for array [66. 69. 76. 72. 79. 77. 74. 77. 71. 79. 74. 66. 67. 78.]  and  [66. 69. 76. 72. 79. 77. 74. 77. 71. 79. 74. 66. 67. 73.]
0.0
for array [66. 69. 76. 72. 79. 77. 74. 77. 71. 79. 74. 66. 67. 78.]  and  [80. 76. 77. 78. 79. 81. 76. 77. 79. 84. 75. 79. 76. 78.]
4.472135954999579
for array [66. 69. 76. 72. 79. 77. 74. 77. 71. 79. 74. 66. 67. 73.]  and  [80. 76. 77. 78. 79. 81. 76. 77. 79. 84. 75. 79. 76. 78.]
4.999999999999999


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in log
  


In [ ]:
np.abs(a1-a2)

array([14.,  7.,  1.,  6.,  0.,  4.,  2.,  0.,  8.,  5.,  1., 13.,  9.,
        0.])

In [ ]:
np.abs(a1-a3)

array([14.,  7.,  1.,  6.,  0.,  4.,  2.,  0.,  8.,  5.,  1., 13.,  9.,
        5.])

In [ ]:
np.log(np.abs(a1-a3))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([2.63905733, 1.94591015, 0.        , 1.79175947,       -inf,
       1.38629436, 0.69314718,       -inf, 2.07944154, 1.60943791,
       0.        , 2.56494936, 2.19722458, 1.60943791])

    Geometric Mean/Median Absolute Error

    Parameters
    ----------
    y_true : pandas Series, pandas DataFrame or NumPy array of
            shape (fh,) or (fh, n_outputs) where fh is the forecasting horizon
        Ground truth (correct) target values.

    y_pred : pandas Series, pandas DataFrame or NumPy array of
            shape (fh,) or (fh, n_outputs) where fh is the forecasting horizon
        Forecasted values.

    y_pred_benchmark : pandas Series, pandas DataFrame or NumPy array of
            shape (fh,) or (fh, n_outputs) where fh is the forecasting horizon
        Forecasted values from benchmark method.

    horizon_weight : array-like of shape (fh,), default=None
        Forecast horizon weights.

    multioutput : {'raw_values', 'uniform_average'}  or array-like of shape \
            (n_outputs,), default='uniform_average'
        Defines aggregating of multiple output values.
        Array-like value defines weights used to average errors.
        If 'raw_values', returns a full set of errors in case of multioutput input.
        If 'uniform_average', errors of all outputs are averaged with uniform weight.

    symmetric : bool, default=False
        Calculates symmetric version of metric if True.

    Returns
    -------
    loss : float
        GMAE loss.
        If multioutput is 'raw_values', then MRAE is returned for each
        output separately.
        If multioutput is 'uniform_average' or an ndarray of weights, then the
        weighted average MRAE of all output errors is returned.
    """

In [ ]:
def geometric_median_absolute_error(
    y_true, y_pred, horizon_weight=None, multioutput="uniform_average", square_root=False, symmetric=False,
):
    _, y_true, y_pred, multioutput = _check_reg_targets(y_true, y_pred, multioutput)
    if horizon_weight is not None:
        check_consistent_length(y_true, horizon_weight)
    try:
        err = np.abs(y_true - y_pred)
        log_err = np.log(err)
        output_errors = np.exp(np.median(log_err))

        if square_root:
            output_errors = np.sqrt(output_errors)

        if isinstance(multioutput, str):
            if multioutput == "raw_values":
            return output_errors
        elif multioutput == "uniform_average":
            # pass None as weights to np.average: uniform mean
            multioutput = None

        return np.average(output_errors, weights=multioutput)

    except:
        print("GeometricMedianAbsoluteError is undefined since two or more groups of corresponding values are same in the arguments passed.")

In [ ]:
def geometric_mean_absolute_error(
    y_true, y_pred, horizon_weight=None, multioutput="uniform_average", square_root=False, symmetric=False,
):  
    _, y_true, y_pred, multioutput = _check_reg_targets(y_true, y_pred, multioutput)
    if horizon_weight is not None:
        check_consistent_length(y_true, horizon_weight)
    try:
        a = np.abs(y_true - y_pred)
        log_a = np.log(a)
        output_errors = np.exp(np.mean(log_a))

        if square_root:
            output_errors = np.sqrt(output_errors)

        if isinstance(multioutput, str):
            if multioutput == "raw_values":
            return output_errors
        elif multioutput == "uniform_average":
            # pass None as weights to np.average: uniform mean
            multioutput = None

        return np.average(output_errors, weights=multioutput)

    except:
        print("GeometricMeanAbsoluteError is undefined since two or more groups of corresponding values are same in the arguments passed.")


In [ ]:
class GeometricMeanAbsoluteError(_ScaledMetricFunctionWrapper):

    def __init__(self):
        name = "GeometricMeanAbsoluteError"
        fn = geometric_mean_absolute_error
        greater_is_better = False
        super(GeometricMeanAbsoluteError, self).__init__(
            fn=fn, name=name, greater_is_better=greater_is_better
        )

class GeometricMedianAbsoluteError(_ScaledMetricFunctionWrapper):

    def __init__(self):
        name = "GeometricMedianAbsoluteError"
        fn = geometric_median_absolute_error
        greater_is_better = False
        super(GeometricMedianAbsoluteError, self).__init__(
            fn=fn, name=name, greater_is_better=greater_is_better
        )
