In [86]:
import pandas as pd
import numpy as np

In [87]:
data = pd.read_csv("/content/drive/MyDrive/Data/for_multi.csv")
data.head(4)

Time  Temperature  Rel_Humidity   S1   S2   S3   S4   S5   S6   S7   S8
0   3.0        20.94         35.98  312  280  504  568  528  647  578  664
1   3.1        20.94         35.98  310  280  504  568  527  647  578  664
2   3.2        20.94         35.98  311  280  503  567  528  648  577  664
3   3.3        20.94         35.98  310  280  503  567  527  648  578  665

In [128]:
data.shape

(2970, 10)

In [88]:
target = data.loc[1:,:]
target.head(4)

Time  Temperature  Rel_Humidity   S1   S2   S3   S4   S5   S6   S7   S8
1   3.1        20.94         35.98  310  280  504  568  527  647  578  664
2   3.2        20.94         35.98  311  280  503  567  528  648  577  664
3   3.3        20.94         35.98  310  280  503  567  527  648  578  665
4   3.4        20.94         35.98  311  280  503  568  528  647  577  664

In [127]:
target.shape

(2969, 10)

In [89]:
data.drop("Time", inplace=True, axis=1)
target.drop("Time", inplace=True, axis=1)
target.reset_index(inplace=True, drop=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4174: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [90]:
target.tail(4)

Temperature  Rel_Humidity   S1   S2   S3   S4   S5   S6   S7   S8
2965        20.93         35.74  330  290  535  576  598  746  650  772
2966        20.93         35.74  330  290  535  575  598  746  650  772
2967        20.93         35.74  331  290  535  575  598  746  650  772
2968        20.93         35.74  329  290  535  575  598  745  649  772

In [92]:
data.tail(4)

Temperature  Rel_Humidity   S1   S2   S3   S4   S5   S6   S7   S8
2966        20.93         35.74  330  290  535  576  598  746  650  772
2967        20.93         35.74  330  290  535  575  598  746  650  772
2968        20.93         35.74  331  290  535  575  598  746  650  772
2969        20.93         35.74  329  290  535  575  598  745  649  772

In [106]:
train_x = data.loc[:2232,:]
train_y = target.loc[:2232,:]
test_x = data.loc[2233:2968,:]
test_y = target.loc[2233:,:]
print(train_x.shape)
print(train_y.shape)
print(test_x.shape)
print(test_y.shape)

(2233, 10)
(2233, 10)
(736, 10)
(736, 10)


In [107]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [108]:
model.fit(train_x, train_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [109]:
model.predict(test_x)

array([[  20.93003163,   35.76987339,  391.11606391, ...,  916.86981484,
         879.9190154 , 1070.74648586],
       [  20.93002039,   35.80903199,  391.43090865, ...,  915.87869502,
         880.19864366, 1070.91858569],
       [  20.92991744,   35.80877032,  391.36591999, ...,  916.85121145,
         879.04712517, 1070.87584695],
       ...,
       [  20.92983256,   35.73927635,  329.47698949, ...,  745.59491152,
         649.84021533,  771.56228304],
       [  20.92998649,   35.73968148,  329.38672449, ...,  745.61729449,
         649.90537452,  771.57322842],
       [  20.9299877 ,   35.7393875 ,  329.77448198, ...,  745.62321329,
         650.03900879,  771.67045325]])

In [129]:
pred_lin = model.predict(test_x)

In [130]:
pred_lin[0,0]

20.930031629822015

In [132]:
pred_lin[0].shape

(10,)

In [110]:
model.score(test_x,test_y)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:434: FutureWarning: The default value of multioutput (not exposed in score method) will change from 'variance_weighted' to 'uniform_average' in 0.23 to keep consistent with 'metrics.r2_score'. To specify the default value manually and avoid the warning, please either call 'metrics.r2_score' directly or make a custom scorer with 'metrics.make_scorer' (the built-in scorer 'r2' uses multioutput='uniform_average').
  "multioutput='uniform_average').", FutureWarning)


0.999843828359222

In [111]:
from sklearn.neighbors import KNeighborsRegressor
model_k = KNeighborsRegressor()

In [112]:
model_k.fit(train_x, train_y)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                    weights='uniform')

In [113]:
model_k.predict(test_x)

array([[  20.93,   35.77,  392.  , ...,  917.2 ,  881.2 , 1071.  ],
       [  20.93,   35.77,  392.  , ...,  917.2 ,  881.2 , 1071.  ],
       [  20.93,   35.77,  392.  , ...,  917.2 ,  881.2 , 1071.  ],
       ...,
       [  20.92,   35.74,  330.6 , ...,  678.2 ,  675.8 ,  791.4 ],
       [  20.92,   35.74,  330.6 , ...,  678.2 ,  675.8 ,  791.4 ],
       [  20.92,   35.74,  330.6 , ...,  678.2 ,  675.8 ,  791.4 ]])

In [114]:
model_k.score(test_x,test_y)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:434: FutureWarning: The default value of multioutput (not exposed in score method) will change from 'variance_weighted' to 'uniform_average' in 0.23 to keep consistent with 'metrics.r2_score'. To specify the default value manually and avoid the warning, please either call 'metrics.r2_score' directly or make a custom scorer with 'metrics.make_scorer' (the built-in scorer 'r2' uses multioutput='uniform_average').
  "multioutput='uniform_average').", FutureWarning)


0.8245281486198375

In [116]:
from sklearn.tree import DecisionTreeRegressor

model_d = DecisionTreeRegressor()

model_d.fit(train_x, train_y)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [117]:
model_d.predict(test_x)

array([[  20.93,   35.77,  392.  , ...,  917.  ,  880.  , 1071.  ],
       [  20.93,   35.77,  391.  , ...,  917.  ,  880.  , 1071.  ],
       [  20.93,   35.77,  392.  , ...,  917.  ,  880.  , 1071.  ],
       ...,
       [  20.92,   35.74,  338.  , ...,  702.  ,  715.  ,  850.  ],
       [  20.92,   35.74,  338.  , ...,  702.  ,  715.  ,  850.  ],
       [  20.92,   35.74,  338.  , ...,  702.  ,  715.  ,  850.  ]])

In [118]:
model_d.score(test_x,test_y)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:434: FutureWarning: The default value of multioutput (not exposed in score method) will change from 'variance_weighted' to 'uniform_average' in 0.23 to keep consistent with 'metrics.r2_score'. To specify the default value manually and avoid the warning, please either call 'metrics.r2_score' directly or make a custom scorer with 'metrics.make_scorer' (the built-in scorer 'r2' uses multioutput='uniform_average').
  "multioutput='uniform_average').", FutureWarning)


0.775136139114446

In [119]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedKFold

In [120]:
model_cross = DecisionTreeRegressor()

In [121]:
cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=1)

In [122]:
n_scores = cross_val_score(model_cross, train_x, train_y, scoring='neg_mean_absolute_error', cv=cv, n_jobs=-1)

In [124]:
from numpy import absolute
from numpy import mean
from numpy import std

In [125]:
n_scores = absolute(n_scores)

In [126]:
# Mean Absolute error
print('MAE: %.3f (%.3f)' % (mean(n_scores), std(n_scores)))

MAE: 0.422 (0.018)


In [134]:
model.predict([data.loc[2969,:].values])

array([[ 20.93002037,  35.73998474, 328.96733925, 290.42110072,
        534.87471414, 575.50633171, 597.4680537 , 744.60603609,
        648.77555516, 771.45760689]])

In [135]:
# Forecasting (LinearRegression Model and can be extended to any model we will be using)
fh_list = []
pred = model.predict([data.loc[2969,:].values])
fh_list.append(pred)

for i in range(5):
  pred = model.predict(pred)
  fh_list.append(pred)

fh_list

[array([[ 20.93002037,  35.73998474, 328.96733925, 290.42110072,
         534.87471414, 575.50633171, 597.4680537 , 744.60603609,
         648.77555516, 771.45760689]]),
 array([[ 20.92996354,  35.73998728, 328.96176516, 290.67842382,
         534.76621953, 575.88296308, 597.00284001, 744.20259253,
         648.52615316, 770.90947335]]),
 array([[ 20.92985155,  35.73997825, 328.9630901 , 290.82482379,
         534.67138333, 576.16604832, 596.58679025, 743.79302036,
         648.26261008, 770.36289736]]),
 array([[ 20.92970058,  35.73994431, 328.96502891, 290.896587  ,
         534.58610265, 576.38100407, 596.2073335 , 743.37967179,
         647.99093714, 769.82159442]]),
 array([[ 20.92952272,  35.73988024, 328.96545806, 290.9185774 ,
         534.50708974, 576.54587084, 595.8554473 , 742.96422317,
         647.71489896, 769.28755485]]),
 array([[ 20.92932699,  35.73978532, 328.96362814, 290.90778373,
         534.43201479, 576.67354464, 595.52462339, 742.54788085,
         647.4369979